source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
pod 'CancellationToken', :path => '../'

target :CancellationTokenExtensionsTests do
  # This Pods library links with a target in another project.
  xcodeproj 'CancellationTokenExtensions'
end
